logic_gates/views/api.py
"""
Author: Matt Guo
Course: EE475/542
Affiliation: University of Washington
Name: api.py
Functionality: A helper flask file for the event that additional expandability
is needed through different routes on the web application. Currently not used.
"""

from functools import wraps
from flask import Blueprint, request, jsonify, session

api_blueprint = Blueprint('api', __name__)

def check_csrf(func):
    """Check to see if a POST method is sent"""
    @wraps(func)
    def wrapper(*args, **kwargs):
        if request.method == 'POST':
            request_data = request.get_json(silent=True, force=True)
            if session.get('csrf') != request_data.get('csrf'):
                return jsonify("Unauthorized request: csrf failed")
        return func(*args, **kwargs)
    return wrapper


@api_blueprint.route('/', methods=['GET', 'POST'])
def index():
    return "API endpoint"

@api_blueprint.route('/switch/<number>', methods=['GET', 'POST'])
@check_csrf
def switch(number):
    """Which of the three switches are used, and return as JSON to the client"""
    if request.method == 'GET':
        return jsonify(success=False, message="not implemented")
    return jsonify(success=True)

@api_blueprint.route('/submit', methods=['GET', 'POST'])
def submit():
    """The submit button action to send the commands via POST over to Flask"""
    if request.method == 'POST':
        asd = request.json
        return jsonify(success=True)
    

logic_gates/views/lab.py
"""
Author: Matt Guo
Course: EE475/542
Affiliation: University of Washington
Name: lab.py
Functionality: The router functionality of the web application, used to initialize the
state of the webpage, as well as call the different python files for UART communication
and video camera feed onto the flask environment.
"""

import secrets
import os
from flask import Blueprint, request, session, render_template, jsonify, Response
lab_blueprint = Blueprint('lab', __name__)
# from .pi_serial import uart_communicate
# from .json_format import formatter

# # import camera driver
# if os.environ.get('CAMERA'):
#     Camera = import_module('camera_' + os.environ['CAMERA']).Camera
# else:
#     from .camera_pi import Camera

@lab_blueprint.route('/', methods=['GET', 'POST'])
def index():
    """THe main initialization of the web application"""

    # # Check to see if a POST method is submitted from the client onto flask
    # if request.method == 'POST':
    #     asd = request.json
    #     # Properly convert the necessary JSON package into a protocol to be sent to the STM32
    #     uart = uart_communicate(asd)
    #     codes = formatter(asd)
    #     print(codes.convert_to_json())
    #     print(codes.convert_to_string())
    #     # Send the response over through serial communication
    #     uart.send_all()
    #     # Return the JSON to the client to indicate the the message transfer is successful
    #     return jsonify(success=True)
    session['csrf'] = secrets.token_urlsafe()
    return render_template("lab.html")
    
def gen(camera):
    """Video streaming generator function."""
    yield b'--frame\r\n'
    while True:
        frame = camera.get_frame()
        yield b'Content-Type: image/jpeg\r\n\r\n' + frame + b'\r\n--frame\r\n'


@lab_blueprint.route('/video_feed')
def video_feed():
    """Video streaming route. Put this in the src attribute of an img tag."""
    return Response(gen(Camera()),
                    mimetype='multipart/x-mixed-replace; boundary=frame')

logic_gates/templates/_bootstrap.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>{{ title }}</title>

    {% block head %}
    {% endblock %}
  </head>
  <body>
    {% block body %}
    {% endblock %}

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
    {% block scripts %}
    {% endblock %}
  </body>
</html>

logic_gates/templates/lab.html
{% extends "_bootstrap.html" %}

{% block head %}
    {{ super() }}
    {# Here go all the styles, CSS links, etc. #}
    {% assets "visir_css" %}
    <link href="{{ ASSET_URL }}" rel="stylesheet">
    {% endassets %}
    <style>
        .breadboard .delete {
            background-image: url("{{ url_for('static', filename='visir/instruments/breadboard/images/trash.png') }}");
        }
    </style>
{% endblock %}

{% block body %}
    {{ super() }}
    {# Here go what is inside the <body></body>. #}

    <div class="container">
        <!--<h1>Virtualized Breadboard</h1>-->
        <div>
            <img src="{{ url_for('static', filename='resources/images/Project_Butterfly.png') }}" height=200px>
            <p id="protocol"></p>
        </div>
        
        <div id="breadboard" style="float:left; padding-right:20px;"></div>
    </div>
    <div>
        <button onclick="printLog()" style="background-color: #4CAF50; border:none; color:white; padding:5px 10px; text-align:center; font-size:14px;">Submit</button>
        <!-- <button onclick="addNotGate(this, 274, 261)" style="padding-left:10px;">Add NOT</button>
        <button onclick="addAndGate(this, 365, 261)" style="padding-left:10px;">Add AND</button>
        <button onclick="addOrGate(this, 456, 261)" style="padding-left:10px;">Add OR</button> -->
    </div>
    <div>
	 <!-- <img src="{{ url_for('lab.video_feed') }}" width="500" height="400" style="padding-top: 10px;"> -->
	</div>
    <div>
        <img src="{{ url_for('static', filename='resources/images/de1_pinout.png')}}" width=400px style="float:left;">
        <img src="{{ url_for('static', filename='resources/images/logic_pinout.png') }}" width=200px style="float:left;">
    </div>

{% endblock %}

{% block scripts %}
    {{ super() }}
    {# Here go all the JavaScript scripts. Most of them should be in the static folder #}

    <script src="https://code.jquery.com/jquery-1.12.4.min.js" integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ=" crossorigin="anonymous"></script>

    <script>
        window.visir = window.visir || {};
        window.visir.BaseLocation = "{{ url_for('static', filename='visir/') }}";
    </script>

    {% assets "visir_js" %}
    <script src="{{ ASSET_URL }}"></script>
    {% endassets %}
    <script src="{{ url_for('static', filename='logic_gates/breadboard-visir.js') }}"></script>
    <script>
        var endpointBase = "{{ url_for('api.index') }}";
        var imageBase = "{{ url_for('static', filename='resources/images/') }}";
        // var numberOfSwitches = 3;
        var numberOfSwitches = 0;
        visir.Config.Set("libraryXml", "{{ url_for('static', filename='logic_gates/library.xml') }}");
        var breadboard = new RHLab.Widgets.Breadboard($("#breadboard"), endpointBase, numberOfSwitches, imageBase, false);
        // var led0 = new RHLab.Widgets.Breadboard.LEDs("LED1", imageBase, 185, 157);
        // var led1 = new RHLab.Widgets.Breadboard.LEDs("LED2", imageBase, 211, 157);
        // breadboard.AddComponent(led0);
        // breadboard.AddComponent(led1);
        // breadboard._leds.push(led0);
        // breadboard._leds.push(led1);
    </script>
    <script>
        // Add an NOT gate to the breadboard GUI, triggered when the "Add NOT Gate" button is pressed
        function addNotGate(b, xPos, yPos){
            var not0 = new RHLab.Widgets.Breadboard.NotGate("NG1", imageBase, xPos, yPos); //274, 261
            breadboard._notGate.push(not0);
            breadboard.AddComponent(not0);
            breadboard.Update();
            b.disabled = true;
        }
        // Add an AND gate to the breadboard GUI, triggered when the "Add AND Gate" button is pressed
        function addAndGate(b, xPos, yPos){
            var and0 = new RHLab.Widgets.Breadboard.AndGate("AG1", imageBase, xPos, yPos);
            // var and0 = new RHLab.Widgets.Breadboard.NotGate("AG1", imageBase, xPos, yPos); // 365, 261
            breadboard._andGate.push(and0);
            // breadboard._notGate.push(and0);
            breadboard.AddComponent(and0);
            breadboard.Update();
            b.disabled = true;
        }
        // Add an OR gate to the breadboard GUI, triggered when the "Add OR Gate" button is pressed
        function addOrGate(b, xPos, yPos){
            var or0 = new RHLab.Widgets.Breadboard.OrGate("OG1", imageBase, xPos, yPos); // 456, 261
            breadboard._orGate.push(or0);
            breadboard.AddComponent(or0);
            breadboard.Update();
            b.disabled = true;
        }
    </script>
    <script src="{{ url_for('static', filename='logic_gates/client_capture.js') }}">
        
    </script>

{% endblock %}